# Generated by Django 4.2.6 on 2024-01-23 14:24

import apps.dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Judul', models.CharField(max_length=100)),
                ('Gambar', models.ImageField(blank=True, null=True, upload_to=apps.dashboard.models.file_image, verbose_name='Photo')),
                ('Deskripsi', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
