# Generated by Django 4.2.6 on 2024-01-18 08:11

import apps.dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_fatwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatwa',
            name='lampiran_fatwa',
            field=models.FileField(upload_to=apps.dashboard.models.upload_to_func),
        ),
        migrations.AlterField(
            model_name='fatwa',
            name='thumbnail',
            field=models.ImageField(upload_to=apps.dashboard.models.upload_to_func),
        ),
        migrations.AlterField(
            model_name='fatwa',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
