# Generated by Django 4.2.6 on 2024-01-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=255)),
                ("deskripsi", models.TextField()),
                ("link_video", models.TextField()),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
